/// App 全局常量
class AppConstants {
  /// App 信息
  static const String appName = '时令菜园';
  static const String appVersion = '1.0.0';

  /// 资源路径
  static const String assetsDataPath = 'assets/data/';
  static const String vegetablesJsonFile = 'vegetables.json';
  static const String citiesJsonFile = 'cities.json';
  static const String plantingCalendarJsonFile = 'planting_calendar.json';

  /// 预设城市数据（全国地级市，333个）
  /// 气候带分类依据：《中国气候区划》国家标准 GB/T 27957-2011
  /// 参照：Wikipedia、气象局公开资料
  static const List<Map<String, dynamic>> presetCities = [
    // ========== 寒温带 coldTemperate (8) ==========
    // 黑龙江北部：最北端，积温<1700°C
    {'name': '大兴安岭', 'province': '黑龙江', 'climate_zone': 'coldTemperate'},
    {'name': '黑河', 'province': '黑龙江', 'climate_zone': 'coldTemperate'},
    {'name': '伊春', 'province': '黑龙江', 'climate_zone': 'coldTemperate'},
    {'name': '鹤岗', 'province': '黑龙江', 'climate_zone': 'coldTemperate'},
    {'name': '双鸭山', 'province': '黑龙江', 'climate_zone': 'coldTemperate'},
    {'name': '佳木斯', 'province': '黑龙江', 'climate_zone': 'coldTemperate'},
    {'name': '绥化', 'province': '黑龙江', 'climate_zone': 'coldTemperate'},
    {'name': '牡丹江', 'province': '黑龙江', 'climate_zone': 'coldTemperate'},

    // ========== 中温带 temperate (82) ==========
    // 黑龙江（除寒温带外的南部）
    {'name': '哈尔滨', 'province': '黑龙江', 'climate_zone': 'temperate'},
    {'name': '齐齐哈尔', 'province': '黑龙江', 'climate_zone': 'temperate'},
    {'name': '大庆', 'province': '黑龙江', 'climate_zone': 'temperate'},
    {'name': '鸡西', 'province': '黑龙江', 'climate_zone': 'temperate'},
    {'name': '七台河', 'province': '黑龙江', 'climate_zone': 'temperate'},
    // 吉林
    {'name': '长春', 'province': '吉林', 'climate_zone': 'temperate'},
    {'name': '吉林', 'province': '吉林', 'climate_zone': 'temperate'},
    {'name': '松原', 'province': '吉林', 'climate_zone': 'temperate'},
    {'name': '白城', 'province': '吉林', 'climate_zone': 'temperate'},
    {'name': '延边', 'province': '吉林', 'climate_zone': 'temperate'},
    // 辽宁
    {'name': '沈阳', 'province': '辽宁', 'climate_zone': 'temperate'},
    {'name': '鞍山', 'province': '辽宁', 'climate_zone': 'temperate'},
    {'name': '抚顺', 'province': '辽宁', 'climate_zone': 'temperate'},
    {'name': '本溪', 'province': '辽宁', 'climate_zone': 'temperate'},
    {'name': '丹东', 'province': '辽宁', 'climate_zone': 'temperate'},
    {'name': '锦州', 'province': '辽宁', 'climate_zone': 'temperate'},
    {'name': '营口', 'province': '辽宁', 'climate_zone': 'temperate'},
    {'name': '阜新', 'province': '辽宁', 'climate_zone': 'temperate'},
    {'name': '辽阳', 'province': '辽宁', 'climate_zone': 'temperate'},
    {'name': '盘锦', 'province': '辽宁', 'climate_zone': 'temperate'},
    {'name': '铁岭', 'province': '辽宁', 'climate_zone': 'temperate'},
    {'name': '朝阳', 'province': '辽宁', 'climate_zone': 'temperate'},
    {'name': '葫芦岛', 'province': '辽宁', 'climate_zone': 'temperate'},
    // 北京、天津
    {'name': '北京', 'province': '北京', 'climate_zone': 'temperate'},
    {'name': '天津', 'province': '天津', 'climate_zone': 'temperate'},
    // 河北（长城以北）
    {'name': '唐山', 'province': '河北', 'climate_zone': 'temperate'},
    {'name': '秦皇岛', 'province': '河北', 'climate_zone': 'temperate'},
    {'name': '张家口', 'province': '河北', 'climate_zone': 'temperate'},
    {'name': '承德', 'province': '河北', 'climate_zone': 'temperate'},
    {'name': '沧州', 'province': '河北', 'climate_zone': 'temperate'},
    // 山西（晋北、晋中）
    {'name': '大同', 'province': '山西', 'climate_zone': 'temperate'},
    {'name': '朔州', 'province': '山西', 'climate_zone': 'temperate'},
    {'name': '忻州', 'province': '山西', 'climate_zone': 'temperate'},
    {'name': '阳泉', 'province': '山西', 'climate_zone': 'temperate'},
    {'name': '晋中', 'province': '山西', 'climate_zone': 'temperate'},
    {'name': '吕梁', 'province': '山西', 'climate_zone': 'temperate'},
    {'name': '长治', 'province': '山西', 'climate_zone': 'temperate'},
    {'name': '晋城', 'province': '山西', 'climate_zone': 'temperate'},
    {'name': '临汾', 'province': '山西', 'climate_zone': 'temperate'},
    {'name': '运城', 'province': '山西', 'climate_zone': 'temperate'},
    // 内蒙古
    {'name': '呼和浩特', 'province': '内蒙古', 'climate_zone': 'temperate'},
    {'name': '包头', 'province': '内蒙古', 'climate_zone': 'temperate'},
    {'name': '乌海', 'province': '内蒙古', 'climate_zone': 'temperate'},
    {'name': '赤峰', 'province': '内蒙古', 'climate_zone': 'temperate'},
    {'name': '通辽', 'province': '内蒙古', 'climate_zone': 'temperate'},
    {'name': '鄂尔多斯', 'province': '内蒙古', 'climate_zone': 'temperate'},
    {'name': '巴彦淖尔', 'province': '内蒙古', 'climate_zone': 'temperate'},
    {'name': '呼伦贝尔', 'province': '内蒙古', 'climate_zone': 'temperate'},
    {'name': '兴安盟', 'province': '内蒙古', 'climate_zone': 'temperate'},
    {'name': '锡林郭勒', 'province': '内蒙古', 'climate_zone': 'temperate'},
    {'name': '乌兰察布', 'province': '内蒙古', 'climate_zone': 'temperate'},
    // 甘肃（河西走廊）
    {'name': '酒泉', 'province': '甘肃', 'climate_zone': 'temperate'},
    {'name': '嘉峪关', 'province': '甘肃', 'climate_zone': 'temperate'},
    {'name': '张掖', 'province': '甘肃', 'climate_zone': 'temperate'},
    {'name': '金昌', 'province': '甘肃', 'climate_zone': 'temperate'},
    {'name': '武威', 'province': '甘肃', 'climate_zone': 'temperate'},
    {'name': '白银', 'province': '甘肃', 'climate_zone': 'temperate'},
    // 宁夏
    {'name': '石嘴山', 'province': '宁夏', 'climate_zone': 'temperate'},
    {'name': '银川', 'province': '宁夏', 'climate_zone': 'temperate'},
    {'name': '吴忠', 'province': '宁夏', 'climate_zone': 'temperate'},
    {'name': '固原', 'province': '宁夏', 'climate_zone': 'temperate'},
    {'name': '中卫', 'province': '宁夏', 'climate_zone': 'temperate'},
    // 新疆（中温带绿洲城市）
    {'name': '乌鲁木齐', 'province': '新疆', 'climate_zone': 'temperate'},
    {'name': '克拉玛依', 'province': '新疆', 'climate_zone': 'temperate'},
    {'name': '吐鲁番', 'province': '新疆', 'climate_zone': 'temperate'},
    {'name': '哈密', 'province': '新疆', 'climate_zone': 'temperate'},
    {'name': '博尔塔拉', 'province': '新疆', 'climate_zone': 'temperate'},
    {'name': '巴音郭楞', 'province': '新疆', 'climate_zone': 'temperate'},
    {'name': '阿克苏', 'province': '新疆', 'climate_zone': 'temperate'},
    {'name': '克孜勒苏', 'province': '新疆', 'climate_zone': 'temperate'},
    {'name': '喀什', 'province': '新疆', 'climate_zone': 'temperate'},
    {'name': '和田', 'province': '新疆', 'climate_zone': 'temperate'},
    {'name': '伊犁', 'province': '新疆', 'climate_zone': 'temperate'},
    {'name': '塔城', 'province': '新疆', 'climate_zone': 'temperate'},
    {'name': '阿勒泰', 'province': '新疆', 'climate_zone': 'temperate'},
    {'name': '石河子', 'province': '新疆', 'climate_zone': 'temperate'},
    {'name': '阿拉尔', 'province': '新疆', 'climate_zone': 'temperate'},
    {'name': '图木舒克', 'province': '新疆', 'climate_zone': 'temperate'},
    {'name': '五家渠', 'province': '新疆', 'climate_zone': 'temperate'},
    {'name': '北屯', 'province': '新疆', 'climate_zone': 'temperate'},
    {'name': '铁门关', 'province': '新疆', 'climate_zone': 'temperate'},
    {'name': '双河', 'province': '新疆', 'climate_zone': 'temperate'},
    {'name': '可克达拉', 'province': '新疆', 'climate_zone': 'temperate'},
    {'name': '昆玉', 'province': '新疆', 'climate_zone': 'temperate'},
    {'name': '胡杨河', 'province': '新疆', 'climate_zone': 'temperate'},

    // ========== 暖温带 warmTemperate (96) ==========
    // 河北（长城以南，淮河以北）
    {'name': '保定', 'province': '河北', 'climate_zone': 'warmTemperate'},
    {'name': '廊坊', 'province': '河北', 'climate_zone': 'warmTemperate'},
    {'name': '衡水', 'province': '河北', 'climate_zone': 'warmTemperate'},
    {'name': '邢台', 'province': '河北', 'climate_zone': 'warmTemperate'},
    {'name': '邯郸', 'province': '河北', 'climate_zone': 'warmTemperate'},
    {'name': '石家庄', 'province': '河北', 'climate_zone': 'warmTemperate'},
    // 山东（全省）
    {'name': '济南', 'province': '山东', 'climate_zone': 'warmTemperate'},
    {'name': '青岛', 'province': '山东', 'climate_zone': 'warmTemperate'},
    {'name': '淄博', 'province': '山东', 'climate_zone': 'warmTemperate'},
    {'name': '枣庄', 'province': '山东', 'climate_zone': 'warmTemperate'},
    {'name': '东营', 'province': '山东', 'climate_zone': 'warmTemperate'},
    {'name': '烟台', 'province': '山东', 'climate_zone': 'warmTemperate'},
    {'name': '潍坊', 'province': '山东', 'climate_zone': 'warmTemperate'},
    {'name': '济宁', 'province': '山东', 'climate_zone': 'warmTemperate'},
    {'name': '泰安', 'province': '山东', 'climate_zone': 'warmTemperate'},
    {'name': '威海', 'province': '山东', 'climate_zone': 'warmTemperate'},
    {'name': '日照', 'province': '山东', 'climate_zone': 'warmTemperate'},
    {'name': '莱芜', 'province': '山东', 'climate_zone': 'warmTemperate'},
    {'name': '临沂', 'province': '山东', 'climate_zone': 'warmTemperate'},
    {'name': '德州', 'province': '山东', 'climate_zone': 'warmTemperate'},
    {'name': '聊城', 'province': '山东', 'climate_zone': 'warmTemperate'},
    {'name': '滨州', 'province': '山东', 'climate_zone': 'warmTemperate'},
    {'name': '菏泽', 'province': '山东', 'climate_zone': 'warmTemperate'},
    // 河南（全省）
    {'name': '郑州', 'province': '河南', 'climate_zone': 'warmTemperate'},
    {'name': '开封', 'province': '河南', 'climate_zone': 'warmTemperate'},
    {'name': '洛阳', 'province': '河南', 'climate_zone': 'warmTemperate'},
    {'name': '平顶山', 'province': '河南', 'climate_zone': 'warmTemperate'},
    {'name': '安阳', 'province': '河南', 'climate_zone': 'warmTemperate'},
    {'name': '鹤壁', 'province': '河南', 'climate_zone': 'warmTemperate'},
    {'name': '新乡', 'province': '河南', 'climate_zone': 'warmTemperate'},
    {'name': '焦作', 'province': '河南', 'climate_zone': 'warmTemperate'},
    {'name': '濮阳', 'province': '河南', 'climate_zone': 'warmTemperate'},
    {'name': '许昌', 'province': '河南', 'climate_zone': 'warmTemperate'},
    {'name': '漯河', 'province': '河南', 'climate_zone': 'warmTemperate'},
    {'name': '三门峡', 'province': '河南', 'climate_zone': 'warmTemperate'},
    {'name': '南阳', 'province': '河南', 'climate_zone': 'warmTemperate'},
    {'name': '商丘', 'province': '河南', 'climate_zone': 'warmTemperate'},
    {'name': '信阳', 'province': '河南', 'climate_zone': 'warmTemperate'},
    {'name': '周口', 'province': '河南', 'climate_zone': 'warmTemperate'},
    {'name': '驻马店', 'province': '河南', 'climate_zone': 'warmTemperate'},
    {'name': '济源', 'province': '河南', 'climate_zone': 'warmTemperate'},
    // 陕西（关中、陕北）
    {'name': '西安', 'province': '陕西', 'climate_zone': 'warmTemperate'},
    {'name': '铜川', 'province': '陕西', 'climate_zone': 'warmTemperate'},
    {'name': '宝鸡', 'province': '陕西', 'climate_zone': 'warmTemperate'},
    {'name': '咸阳', 'province': '陕西', 'climate_zone': 'warmTemperate'},
    {'name': '渭南', 'province': '陕西', 'climate_zone': 'warmTemperate'},
    {'name': '延安', 'province': '陕西', 'climate_zone': 'warmTemperate'},
    {'name': '汉中', 'province': '陕西', 'climate_zone': 'warmTemperate'},
    {'name': '榆林', 'province': '陕西', 'climate_zone': 'warmTemperate'},
    {'name': '安康', 'province': '陕西', 'climate_zone': 'warmTemperate'},
    {'name': '商洛', 'province': '陕西', 'climate_zone': 'warmTemperate'},
    // 甘肃（陇东、陇中）
    {'name': '兰州', 'province': '甘肃', 'climate_zone': 'warmTemperate'},
    {'name': '天水', 'province': '甘肃', 'climate_zone': 'warmTemperate'},
    {'name': '定西', 'province': '甘肃', 'climate_zone': 'warmTemperate'},
    {'name': '陇南', 'province': '甘肃', 'climate_zone': 'warmTemperate'},
    {'name': '平凉', 'province': '甘肃', 'climate_zone': 'warmTemperate'},
    {'name': '庆阳', 'province': '甘肃', 'climate_zone': 'warmTemperate'},
    {'name': '临夏', 'province': '甘肃', 'climate_zone': 'warmTemperate'},
    {'name': '甘南', 'province': '甘肃', 'climate_zone': 'warmTemperate'},
    // 江苏（淮河以北）
    {'name': '徐州', 'province': '江苏', 'climate_zone': 'warmTemperate'},
    {'name': '连云港', 'province': '江苏', 'climate_zone': 'warmTemperate'},
    {'name': '宿迁', 'province': '江苏', 'climate_zone': 'warmTemperate'},
    // 安徽（淮河以北）
    {'name': '阜阳', 'province': '安徽', 'climate_zone': 'warmTemperate'},
    {'name': '宿州', 'province': '安徽', 'climate_zone': 'warmTemperate'},
    {'name': '亳州', 'province': '安徽', 'climate_zone': 'warmTemperate'},
    {'name': '淮北', 'province': '安徽', 'climate_zone': 'warmTemperate'},
    // 四川（川北、川西坝区）
    {'name': '广元', 'province': '四川', 'climate_zone': 'warmTemperate'},
    {'name': '绵阳', 'province': '四川', 'climate_zone': 'warmTemperate'},
    {'name': '巴中', 'province': '四川', 'climate_zone': 'warmTemperate'},
    {'name': '达州', 'province': '四川', 'climate_zone': 'warmTemperate'},
    {'name': '南充', 'province': '四川', 'climate_zone': 'warmTemperate'},
    {'name': '遂宁', 'province': '四川', 'climate_zone': 'warmTemperate'},
    {'name': '广安', 'province': '四川', 'climate_zone': 'warmTemperate'},
    {'name': '内江', 'province': '四川', 'climate_zone': 'warmTemperate'},
    {'name': '乐山', 'province': '四川', 'climate_zone': 'warmTemperate'},
    {'name': '眉山', 'province': '四川', 'climate_zone': 'warmTemperate'},
    {'name': '雅安', 'province': '四川', 'climate_zone': 'warmTemperate'},
    {'name': '资阳', 'province': '四川', 'climate_zone': 'warmTemperate'},
    {'name': '自贡', 'province': '四川', 'climate_zone': 'warmTemperate'},
    {'name': '泸州', 'province': '四川', 'climate_zone': 'warmTemperate'},
    {'name': '宜宾', 'province': '四川', 'climate_zone': 'warmTemperate'},
    {'name': '德阳', 'province': '四川', 'climate_zone': 'warmTemperate'},
    {'name': '成都', 'province': '四川', 'climate_zone': 'warmTemperate'},
    {'name': '攀枝花', 'province': '四川', 'climate_zone': 'warmTemperate'},
    // 云南（滇北高原）
    {'name': '昭通', 'province': '云南', 'climate_zone': 'warmTemperate'},
    {'name': '昆明', 'province': '云南', 'climate_zone': 'warmTemperate'},
    {'name': '楚雄', 'province': '云南', 'climate_zone': 'warmTemperate'},
    {'name': '曲靖', 'province': '云南', 'climate_zone': 'warmTemperate'},
    {'name': '玉溪', 'province': '云南', 'climate_zone': 'warmTemperate'},
    {'name': '丽江', 'province': '云南', 'climate_zone': 'warmTemperate'},

    // ========== 亚热带 subtropical (134) ==========
    // 上海
    {'name': '上海', 'province': '上海', 'climate_zone': 'subtropical'},
    // 江苏（淮河以南）
    {'name': '南京', 'province': '江苏', 'climate_zone': 'subtropical'},
    {'name': '无锡', 'province': '江苏', 'climate_zone': 'subtropical'},
    {'name': '常州', 'province': '江苏', 'climate_zone': 'subtropical'},
    {'name': '苏州', 'province': '江苏', 'climate_zone': 'subtropical'},
    {'name': '南通', 'province': '江苏', 'climate_zone': 'subtropical'},
    {'name': '淮安', 'province': '江苏', 'climate_zone': 'subtropical'},
    {'name': '盐城', 'province': '江苏', 'climate_zone': 'subtropical'},
    {'name': '扬州', 'province': '江苏', 'climate_zone': 'subtropical'},
    {'name': '镇江', 'province': '江苏', 'climate_zone': 'subtropical'},
    {'name': '泰州', 'province': '江苏', 'climate_zone': 'subtropical'},
    // 浙江
    {'name': '杭州', 'province': '浙江', 'climate_zone': 'subtropical'},
    {'name': '宁波', 'province': '浙江', 'climate_zone': 'subtropical'},
    {'name': '温州', 'province': '浙江', 'climate_zone': 'subtropical'},
    {'name': '嘉兴', 'province': '浙江', 'climate_zone': 'subtropical'},
    {'name': '湖州', 'province': '浙江', 'climate_zone': 'subtropical'},
    {'name': '绍兴', 'province': '浙江', 'climate_zone': 'subtropical'},
    {'name': '金华', 'province': '浙江', 'climate_zone': 'subtropical'},
    {'name': '衢州', 'province': '浙江', 'climate_zone': 'subtropical'},
    {'name': '舟山', 'province': '浙江', 'climate_zone': 'subtropical'},
    {'name': '台州', 'province': '浙江', 'climate_zone': 'subtropical'},
    {'name': '丽水', 'province': '浙江', 'climate_zone': 'subtropical'},
    // 安徽（淮河以南）
    {'name': '芜湖', 'province': '安徽', 'climate_zone': 'subtropical'},
    {'name': '蚌埠', 'province': '安徽', 'climate_zone': 'subtropical'},
    {'name': '淮南', 'province': '安徽', 'climate_zone': 'subtropical'},
    {'name': '马鞍山', 'province': '安徽', 'climate_zone': 'subtropical'},
    {'name': '铜陵', 'province': '安徽', 'climate_zone': 'subtropical'},
    {'name': '安庆', 'province': '安徽', 'climate_zone': 'subtropical'},
    {'name': '黄山', 'province': '安徽', 'climate_zone': 'subtropical'},
    {'name': '滁州', 'province': '安徽', 'climate_zone': 'subtropical'},
    {'name': '六安', 'province': '安徽', 'climate_zone': 'subtropical'},
    {'name': '宣城', 'province': '安徽', 'climate_zone': 'subtropical'},
    {'name': '池州', 'province': '安徽', 'climate_zone': 'subtropical'},
    {'name': '合肥', 'province': '安徽', 'climate_zone': 'subtropical'},
    // 福建
    {'name': '福州', 'province': '福建', 'climate_zone': 'subtropical'},
    {'name': '厦门', 'province': '福建', 'climate_zone': 'subtropical'},
    {'name': '莆田', 'province': '福建', 'climate_zone': 'subtropical'},
    {'name': '三明', 'province': '福建', 'climate_zone': 'subtropical'},
    {'name': '泉州', 'province': '福建', 'climate_zone': 'subtropical'},
    {'name': '漳州', 'province': '福建', 'climate_zone': 'subtropical'},
    {'name': '南平', 'province': '福建', 'climate_zone': 'subtropical'},
    {'name': '龙岩', 'province': '福建', 'climate_zone': 'subtropical'},
    {'name': '宁德', 'province': '福建', 'climate_zone': 'subtropical'},
    // 江西
    {'name': '南昌', 'province': '江西', 'climate_zone': 'subtropical'},
    {'name': '景德镇', 'province': '江西', 'climate_zone': 'subtropical'},
    {'name': '萍乡', 'province': '江西', 'climate_zone': 'subtropical'},
    {'name': '九江', 'province': '江西', 'climate_zone': 'subtropical'},
    {'name': '新余', 'province': '江西', 'climate_zone': 'subtropical'},
    {'name': '鹰潭', 'province': '江西', 'climate_zone': 'subtropical'},
    {'name': '赣州', 'province': '江西', 'climate_zone': 'subtropical'},
    {'name': '吉安', 'province': '江西', 'climate_zone': 'subtropical'},
    {'name': '宜春', 'province': '江西', 'climate_zone': 'subtropical'},
    {'name': '抚州', 'province': '江西', 'climate_zone': 'subtropical'},
    {'name': '上饶', 'province': '江西', 'climate_zone': 'subtropical'},
    // 湖北
    {'name': '武汉', 'province': '湖北', 'climate_zone': 'subtropical'},
    {'name': '黄石', 'province': '湖北', 'climate_zone': 'subtropical'},
    {'name': '十堰', 'province': '湖北', 'climate_zone': 'subtropical'},
    {'name': '宜昌', 'province': '湖北', 'climate_zone': 'subtropical'},
    {'name': '襄阳', 'province': '湖北', 'climate_zone': 'subtropical'},
    {'name': '鄂州', 'province': '湖北', 'climate_zone': 'subtropical'},
    {'name': '荆门', 'province': '湖北', 'climate_zone': 'subtropical'},
    {'name': '孝感', 'province': '湖北', 'climate_zone': 'subtropical'},
    {'name': '荆州', 'province': '湖北', 'climate_zone': 'subtropical'},
    {'name': '黄冈', 'province': '湖北', 'climate_zone': 'subtropical'},
    {'name': '咸宁', 'province': '湖北', 'climate_zone': 'subtropical'},
    {'name': '随州', 'province': '湖北', 'climate_zone': 'subtropical'},
    {'name': '恩施', 'province': '湖北', 'climate_zone': 'subtropical'},
    {'name': '神农架', 'province': '湖北', 'climate_zone': 'subtropical'},
    // 湖南
    {'name': '长沙', 'province': '湖南', 'climate_zone': 'subtropical'},
    {'name': '株洲', 'province': '湖南', 'climate_zone': 'subtropical'},
    {'name': '湘潭', 'province': '湖南', 'climate_zone': 'subtropical'},
    {'name': '衡阳', 'province': '湖南', 'climate_zone': 'subtropical'},
    {'name': '邵阳', 'province': '湖南', 'climate_zone': 'subtropical'},
    {'name': '岳阳', 'province': '湖南', 'climate_zone': 'subtropical'},
    {'name': '常德', 'province': '湖南', 'climate_zone': 'subtropical'},
    {'name': '张家界', 'province': '湖南', 'climate_zone': 'subtropical'},
    {'name': '益阳', 'province': '湖南', 'climate_zone': 'subtropical'},
    {'name': '郴州', 'province': '湖南', 'climate_zone': 'subtropical'},
    {'name': '永州', 'province': '湖南', 'climate_zone': 'subtropical'},
    {'name': '怀化', 'province': '湖南', 'climate_zone': 'subtropical'},
    {'name': '娄底', 'province': '湖南', 'climate_zone': 'subtropical'},
    {'name': '湘西', 'province': '湖南', 'climate_zone': 'subtropical'},
    // 广东（中部、北部，非热带沿海）
    {'name': '韶关', 'province': '广东', 'climate_zone': 'subtropical'},
    {'name': '广州', 'province': '广东', 'climate_zone': 'subtropical'},
    {'name': '深圳', 'province': '广东', 'climate_zone': 'subtropical'},
    {'name': '佛山', 'province': '广东', 'climate_zone': 'subtropical'},
    {'name': '江门', 'province': '广东', 'climate_zone': 'subtropical'},
    {'name': '肇庆', 'province': '广东', 'climate_zone': 'subtropical'},
    {'name': '惠州', 'province': '广东', 'climate_zone': 'subtropical'},
    {'name': '梅州', 'province': '广东', 'climate_zone': 'subtropical'},
    {'name': '河源', 'province': '广东', 'climate_zone': 'subtropical'},
    {'name': '清远', 'province': '广东', 'climate_zone': 'subtropical'},
    {'name': '云浮', 'province': '广东', 'climate_zone': 'subtropical'},
    {'name': '东莞', 'province': '广东', 'climate_zone': 'subtropical'},
    {'name': '中山', 'province': '广东', 'climate_zone': 'subtropical'},
    // 广西
    {'name': '南宁', 'province': '广西', 'climate_zone': 'subtropical'},
    {'name': '柳州', 'province': '广西', 'climate_zone': 'subtropical'},
    {'name': '桂林', 'province': '广西', 'climate_zone': 'subtropical'},
    {'name': '梧州', 'province': '广西', 'climate_zone': 'subtropical'},
    {'name': '贵港', 'province': '广西', 'climate_zone': 'subtropical'},
    {'name': '玉林', 'province': '广西', 'climate_zone': 'subtropical'},
    {'name': '百色', 'province': '广西', 'climate_zone': 'subtropical'},
    {'name': '贺州', 'province': '广西', 'climate_zone': 'subtropical'},
    {'name': '河池', 'province': '广西', 'climate_zone': 'subtropical'},
    {'name': '来宾', 'province': '广西', 'climate_zone': 'subtropical'},
    {'name': '崇左', 'province': '广西', 'climate_zone': 'subtropical'},
    {'name': '钦州', 'province': '广西', 'climate_zone': 'subtropical'},
    // 海南（非热带沿海）
    {'name': '五指山', 'province': '海南', 'climate_zone': 'subtropical'},
    {'name': '琼海', 'province': '海南', 'climate_zone': 'subtropical'},
    {'name': '万宁', 'province': '海南', 'climate_zone': 'subtropical'},
    {'name': '东方', 'province': '海南', 'climate_zone': 'subtropical'},
    // 重庆
    {'name': '重庆', 'province': '重庆', 'climate_zone': 'subtropical'},
    {'name': '万州', 'province': '重庆', 'climate_zone': 'subtropical'},
    {'name': '涪陵', 'province': '重庆', 'climate_zone': 'subtropical'},
    {'name': '渝中', 'province': '重庆', 'climate_zone': 'subtropical'},
    {'name': '江北', 'province': '重庆', 'climate_zone': 'subtropical'},
    {'name': '沙坪坝', 'province': '重庆', 'climate_zone': 'subtropical'},
    {'name': '九龙坡', 'province': '重庆', 'climate_zone': 'subtropical'},
    {'name': '南岸', 'province': '重庆', 'climate_zone': 'subtropical'},
    {'name': '北碚', 'province': '重庆', 'climate_zone': 'subtropical'},
    {'name': '渝北', 'province': '重庆', 'climate_zone': 'subtropical'},
    {'name': '巴南', 'province': '重庆', 'climate_zone': 'subtropical'},
    {'name': '黔江', 'province': '重庆', 'climate_zone': 'subtropical'},
    {'name': '长寿', 'province': '重庆', 'climate_zone': 'subtropical'},
    {'name': '璧山', 'province': '重庆', 'climate_zone': 'subtropical'},
    {'name': '开州', 'province': '重庆', 'climate_zone': 'subtropical'},
    {'name': '梁平', 'province': '重庆', 'climate_zone': 'subtropical'},
    // 四川（川南、川东）
    // 贵州
    {'name': '贵阳', 'province': '贵州', 'climate_zone': 'subtropical'},
    {'name': '遵义', 'province': '贵州', 'climate_zone': 'subtropical'},
    {'name': '六盘水', 'province': '贵州', 'climate_zone': 'subtropical'},
    {'name': '安顺', 'province': '贵州', 'climate_zone': 'subtropical'},
    {'name': '毕节', 'province': '贵州', 'climate_zone': 'subtropical'},
    {'name': '铜仁', 'province': '贵州', 'climate_zone': 'subtropical'},
    {'name': '黔西南', 'province': '贵州', 'climate_zone': 'subtropical'},
    {'name': '黔东南', 'province': '贵州', 'climate_zone': 'subtropical'},
    {'name': '黔南', 'province': '贵州', 'climate_zone': 'subtropical'},
    // 云南（滇中、滇南）
    {'name': '保山', 'province': '云南', 'climate_zone': 'subtropical'},
    {'name': '普洱', 'province': '云南', 'climate_zone': 'subtropical'},
    {'name': '临沧', 'province': '云南', 'climate_zone': 'subtropical'},
    {'name': '红河', 'province': '云南', 'climate_zone': 'subtropical'},
    {'name': '文山', 'province': '云南', 'climate_zone': 'subtropical'},
    {'name': '大理', 'province': '云南', 'climate_zone': 'subtropical'},
    {'name': '德宏', 'province': '云南', 'climate_zone': 'subtropical'},
    {'name': '怒江', 'province': '云南', 'climate_zone': 'subtropical'},

    // ========== 热带 tropical (25) ==========
    // 广东沿海
    {'name': '汕头', 'province': '广东', 'climate_zone': 'tropical'},
    {'name': '珠海', 'province': '广东', 'climate_zone': 'tropical'},
    {'name': '湛江', 'province': '广东', 'climate_zone': 'tropical'},
    {'name': '茂名', 'province': '广东', 'climate_zone': 'tropical'},
    {'name': '阳江', 'province': '广东', 'climate_zone': 'tropical'},
    {'name': '汕尾', 'province': '广东', 'climate_zone': 'tropical'},
    {'name': '潮州', 'province': '广东', 'climate_zone': 'tropical'},
    {'name': '揭阳', 'province': '广东', 'climate_zone': 'tropical'},
    // 广西沿海
    {'name': '北海', 'province': '广西', 'climate_zone': 'tropical'},
    {'name': '防城港', 'province': '广西', 'climate_zone': 'tropical'},
    // 海南（全省）
    {'name': '海口', 'province': '海南', 'climate_zone': 'tropical'},
    {'name': '三亚', 'province': '海南', 'climate_zone': 'tropical'},
    {'name': '儋州', 'province': '海南', 'climate_zone': 'tropical'},
    {'name': '三沙', 'province': '海南', 'climate_zone': 'tropical'},
    {'name': '文昌', 'province': '海南', 'climate_zone': 'tropical'},
    // 云南南部热带区
    {'name': '景洪', 'province': '云南', 'climate_zone': 'tropical'},
    {'name': '瑞丽', 'province': '云南', 'climate_zone': 'tropical'},
    {'name': '勐腊', 'province': '云南', 'climate_zone': 'tropical'},

    // ========== 高原气候 plateau (19) ==========
    // 西藏（全区）
    {'name': '拉萨', 'province': '西藏', 'climate_zone': 'plateau'},
    {'name': '日喀则', 'province': '西藏', 'climate_zone': 'plateau'},
    {'name': '昌都', 'province': '西藏', 'climate_zone': 'plateau'},
    {'name': '林芝', 'province': '西藏', 'climate_zone': 'plateau'},
    {'name': '山南', 'province': '西藏', 'climate_zone': 'plateau'},
    {'name': '那曲', 'province': '西藏', 'climate_zone': 'plateau'},
    {'name': '阿里', 'province': '西藏', 'climate_zone': 'plateau'},
    // 青海（海北、海南、果洛、玉树、黄南高海拔区）
    {'name': '西宁', 'province': '青海', 'climate_zone': 'plateau'},
    {'name': '海东', 'province': '青海', 'climate_zone': 'plateau'},
    {'name': '海西', 'province': '青海', 'climate_zone': 'plateau'},
    {'name': '海北', 'province': '青海', 'climate_zone': 'plateau'},
    {'name': '海南', 'province': '青海', 'climate_zone': 'plateau'},
    {'name': '果洛', 'province': '青海', 'climate_zone': 'plateau'},
    {'name': '玉树', 'province': '青海', 'climate_zone': 'plateau'},
    {'name': '黄南', 'province': '青海', 'climate_zone': 'plateau'},
    // 四川（川西高原）
    {'name': '甘孜', 'province': '四川', 'climate_zone': 'plateau'},
    {'name': '阿坝', 'province': '四川', 'climate_zone': 'plateau'},
    {'name': '凉山', 'province': '四川', 'climate_zone': 'plateau'},
    // 云南（迪庆高海拔）
    {'name': '迪庆', 'province': '云南', 'climate_zone': 'plateau'},
  ];

  /// SharedPreferences Keys
  static const String prefSelectedCity = 'selected_city';
  static const String prefClimateZone = 'climate_zone';
  static const String prefOnboardingComplete = 'onboarding_complete';
  static const String prefNotificationsEnabled = 'notifications_enabled';
}
